deploy backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -313,73 +313,94 @@ jobs:
       - destroy-environment
       - revert-migrations  
 
-  smoke-test:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Backend smoke test.
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-            if curl -s $API_URL/api/status | grep "ok"
-            then
-              exit 0
-            else
-              exit 1
-            fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-            then
-              exit 0
-            else
-              exit 1
-            fi
-      - destroy-environment
-      - revert-migrations
-      - notify_on_failure  
+  # smoke-test:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - install_nodejs
+  #     - run:
+  #         name: Backend smoke test.
+  #         command: |
+  #           export BACKEND_IP=$(aws ec2 describe-instances \
+  #             --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --query 'Reservations[*].Instances[*].PublicDnsName' --output text)
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #           echo "${API_URL}"
+  #           if curl "${API_URL}/api/status" | grep "ok"
+  #           then
+  #             exit 0
+  #           else
+  #             exit 1
+  #           fi
+  #     - run:
+  #         name: Frontend smoke test.
+  #         command: |
+  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+  #           echo ${URL} 
+  #           if curl -s ${URL} | grep "Welcome"
+  #           then
+  #               # Change this to 0 after the job fails
+  #             exit 0
+  #           else
+  #             exit 1
+  #           fi
+  #     - destroy-environment
+  #     - revert-migrations
+   
 
 #   cloudfront-update:
 #     docker:
-#       # Docker image here that supports AWS CLI
+#       - image: cimg/base:stable
 #     steps:
-#       # Checkout code from git
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
 #       - run:
-#           name: Install dependencies
+#           name: Store old workflow ID to kvdb
 #           command: |
-#             # your code here
+#             export OldWorkflowID=$(aws cloudformation \
+#               list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+#               --no-paginate --output text)
+#             echo "OldWorkflowID: ${OldWorkflowID}"
+#             curl https://kvdb.io/YLTX6K5V1r7UY1NrHHKrHo/old_workflowid -d "${OldWorkflowID}"
+      
 #       - run:
 #           name: Update cloudfront distribution
 #           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+#             aws cloudformation deploy \
+#             --template-file .circleci/files/cloudfront.yml \
+#             --stack-name InitialStack \
+#             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+#             --tags project=udapeople
+#       - destroy-environment:
+#           workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+#       - revert-migrations:
+#           workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
 
 # cleanup:
 #     docker:
-#       # Docker image here
+#       - image: cimg/base:stable
 #     steps:
-#       # Checkout code from git
+#       - checkout
+#       - install_awscli
 #       - run:
 #           name: Get old stack workflow id
 #           command: |
-#             # your code here
-#             export OldWorkflowID="the id here"
-#             export STACKS=[] #put the list of stacks here
-#       - run:
-#           name: Remove old stacks and files
-#           command: |
+#             export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+#             --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+#             echo Stack names: "${STACKS[@]}"
+#             export OldWorkflowID=$(curl --insecure https://kvdb.io/YLTX6K5V1r7UY1NrHHKrHo/old_workflowid)
+#             echo Old Workflow ID: $OldWorkflowID  
 #             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
 #             then
-#               # your code here
+#               echo "-------------Cleaning up old resources-------------"
+#               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+#               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+#               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+#             else
+#               echo "-------------Nothing to Cleanup-------------"
 #             fi
             
 
